-- liquibase formatted sql

-- changeset john:Initial context:demo
CREATE TABLE UXI_FEATURE_CARDS_LU (
    CARD_TEXT VARCHAR2(255 BYTE)
   ,CARD_IMAGE VARCHAR2(255 BYTE)
   ,CARD_CATEGORY VARCHAR2(255 BYTE)
   ,CARD_SUBTEXT VARCHAR2(255 BYTE)
   ,CARD_ORDER NUMBER
);