-- liquibase formatted sql

-- changeset john:Initial context:demo
CREATE TABLE UXI_AUTHN_METHODS_LU (
   ID NUMBER NOT NULL
  ,METHOD VARCHAR2(255 BYTE) NOT NULL
  ,DESCRIPTION VARCHAR2(4000 BYTE)
  ,CONSTRAINT AUTHN_METHODS_PK PRIMARY KEY (ID)
);