-- liquibase formatted sql

-- changeset gotsysdba:Initial
ALTER USER "DEMO" GRANT CONNECT THROUGH ADMIN;
ALTER USER "DEMO" QUOTA UNLIMITED ON "DATA";
GRANT CREATE SESSION TO "DEMO";
GRANT CREATE TABLE TO "DEMO";
GRANT CREATE CLUSTER TO "DEMO";
GRANT CREATE SYNONYM TO "DEMO";
GRANT CREATE VIEW TO "DEMO";
GRANT CREATE SEQUENCE TO "DEMO";
GRANT CREATE PROCEDURE TO "DEMO";
GRANT CREATE TRIGGER TO "DEMO";
GRANT CREATE MATERIALIZED VIEW TO "DEMO";
GRANT CREATE TYPE TO "DEMO";
GRANT CREATE OPERATOR TO "DEMO";
GRANT CREATE INDEXTYPE TO "DEMO";
GRANT CREATE DIMENSION TO "DEMO";
GRANT CREATE JOB TO "DEMO";

--rollback ALTER USER "DEMO" REVOKE CONNECT THROUGH ADMIN;
--rollback ALTER USER "DEMO" QUOTA 0 ON "DATA";
--rollback REVOKE CREATE SESSION FROM "DEMO";
--rollback REVOKE CREATE TABLE FROM "DEMO";
--rollback REVOKE CREATE CLUSTER FROM "DEMO";
--rollback REVOKE CREATE SYNONYM FROM "DEMO";
--rollback REVOKE CREATE VIEW FROM "DEMO";
--rollback REVOKE CREATE SEQUENCE FROM "DEMO";
--rollback REVOKE CREATE PROCEDURE FROM "DEMO";
--rollback REVOKE CREATE TRIGGER FROM "DEMO";
--rollback REVOKE CREATE MATERIALIZED VIEW FROM "DEMO";
--rollback REVOKE CREATE TYPE FROM "DEMO";
--rollback REVOKE CREATE OPERATOR FROM "DEMO";
--rollback REVOKE CREATE INDEXTYPE FROM "DEMO";
--rollback REVOKE CREATE DIMENSION FROM "DEMO";
--rollback REVOKE CREATE JOB FROM "DEMO";