-- liquibase formatted sql

-- changeset john:Initial context:demo
CREATE TABLE UXI_ORDERS_LU (
    ORDER_ID NUMBER NOT NULL
   ,CUSTOMER_ID NUMBER NOT NULL
   ,ORDER_TOTAL NUMBER(8, 2)
   ,ORDER_TIMESTAMP TIMESTAMP(6)
   ,USER_NAME VARCHAR2(100 BYTE)
   ,TAGS VARCHAR2(4000 BYTE)
   ,CONSTRAINT UXI_ORDER_PK PRIMARY KEY (ORDER_ID)
);